# You can use *-dev.yml for your development sources
sources:
  - source: 12345678-9abc-def0-1234-1234567890ab
    access_key_id: access_key_id
    secret_access_key: secret_access_key
  - source: 12345678-9abc-def0-abcd-1234567890ab
    access_key_id: access_key_id
    secret_access_key: secret_access_key
